name: testing

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      -main
  workflow_dispatch:

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: github_action_pratice/abc
        
      - name: Run pwd1
        run: pwd

      - name: ls
        run: ls

      - name: cd
        run: cd abc
        
      - name: cat
        run: cat abc/test.txt

      - name: Run pwd2
        run: pwd
